
build:
  tags:
    - GO1.14
  script:
    - go generate -v
    - go build -v "-ldflags=-H windowsgui -w -s" -trimpath
  artifacts:
    expire_in: 1 day
    name: JenkinsCheck
    paths:
      - 'JenkinsCheck.exe'
